# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client/designer_ui/index.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(663, 544)
        self.index = QtWidgets.QTabWidget(main)
        self.index.setGeometry(QtCore.QRect(0, 0, 751, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index.sizePolicy().hasHeightForWidth())
        self.index.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.index.setFont(font)
        self.index.setAcceptDrops(False)
        self.index.setTabPosition(QtWidgets.QTabWidget.North)
        self.index.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.index.setDocumentMode(False)
        self.index.setTabsClosable(False)
        self.index.setMovable(True)
        self.index.setTabBarAutoHide(False)
        self.index.setObjectName("index")
        self.users_tab = QtWidgets.QWidget()
        self.users_tab.setObjectName("users_tab")
        self.email_label = QtWidgets.QLabel(self.users_tab)
        self.email_label.setGeometry(QtCore.QRect(40, 130, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.email_line_edit = QtWidgets.QLineEdit(self.users_tab)
        self.email_line_edit.setEnabled(False)
        self.email_line_edit.setGeometry(QtCore.QRect(20, 150, 240, 20))
        self.email_line_edit.setText("")
        self.email_line_edit.setFrame(False)
        self.email_line_edit.setObjectName("email_line_edit")
        self.address_label = QtWidgets.QLabel(self.users_tab)
        self.address_label.setGeometry(QtCore.QRect(40, 190, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.address_label.setFont(font)
        self.address_label.setObjectName("address_label")
        self.address_line_edit = QtWidgets.QLineEdit(self.users_tab)
        self.address_line_edit.setEnabled(False)
        self.address_line_edit.setGeometry(QtCore.QRect(20, 210, 240, 20))
        self.address_line_edit.setText("")
        self.address_line_edit.setFrame(False)
        self.address_line_edit.setObjectName("address_line_edit")
        self.birth_date_label = QtWidgets.QLabel(self.users_tab)
        self.birth_date_label.setGeometry(QtCore.QRect(40, 250, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.birth_date_label.setFont(font)
        self.birth_date_label.setObjectName("birth_date_label")
        self.documents_label = QtWidgets.QLabel(self.users_tab)
        self.documents_label.setGeometry(QtCore.QRect(40, 310, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.documents_label.setFont(font)
        self.documents_label.setObjectName("documents_label")
        self.first_name_label = QtWidgets.QLabel(self.users_tab)
        self.first_name_label.setGeometry(QtCore.QRect(40, 0, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.first_name_label.setFont(font)
        self.first_name_label.setObjectName("first_name_label")
        self.first_name_line_edit = QtWidgets.QLineEdit(self.users_tab)
        self.first_name_line_edit.setEnabled(False)
        self.first_name_line_edit.setGeometry(QtCore.QRect(20, 20, 240, 20))
        self.first_name_line_edit.setText("")
        self.first_name_line_edit.setFrame(False)
        self.first_name_line_edit.setObjectName("first_name_line_edit")
        self.middle_name_label = QtWidgets.QLabel(self.users_tab)
        self.middle_name_label.setGeometry(QtCore.QRect(40, 90, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.middle_name_label.setFont(font)
        self.middle_name_label.setObjectName("middle_name_label")
        self.middle_name_line_edit = QtWidgets.QLineEdit(self.users_tab)
        self.middle_name_line_edit.setEnabled(False)
        self.middle_name_line_edit.setGeometry(QtCore.QRect(20, 110, 240, 20))
        self.middle_name_line_edit.setText("")
        self.middle_name_line_edit.setFrame(False)
        self.middle_name_line_edit.setObjectName("middle_name_line_edit")
        self.surname_label = QtWidgets.QLabel(self.users_tab)
        self.surname_label.setGeometry(QtCore.QRect(40, 50, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.surname_label.setFont(font)
        self.surname_label.setObjectName("surname_label")
        self.surname_line_edit = QtWidgets.QLineEdit(self.users_tab)
        self.surname_line_edit.setEnabled(False)
        self.surname_line_edit.setGeometry(QtCore.QRect(20, 70, 240, 20))
        self.surname_line_edit.setText("")
        self.surname_line_edit.setFrame(False)
        self.surname_line_edit.setObjectName("surname_line_edit")
        self.select_user_combo_box = QtWidgets.QComboBox(self.users_tab)
        self.select_user_combo_box.setGeometry(QtCore.QRect(360, 60, 251, 21))
        self.select_user_combo_box.setObjectName("select_user_combo_box")
        self.documents_list_widget = QtWidgets.QListWidget(self.users_tab)
        self.documents_list_widget.setGeometry(QtCore.QRect(20, 330, 251, 81))
        self.documents_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.documents_list_widget.setObjectName("documents_list_widget")
        self.select_user_label = QtWidgets.QLabel(self.users_tab)
        self.select_user_label.setGeometry(QtCore.QRect(440, 30, 81, 16))
        self.select_user_label.setObjectName("select_user_label")
        self.clear_docs_push_button = QtWidgets.QPushButton(self.users_tab)
        self.clear_docs_push_button.setGeometry(QtCore.QRect(20, 450, 75, 23))
        self.clear_docs_push_button.setObjectName("clear_docs_push_button")
        self.apply_docs_push_button = QtWidgets.QPushButton(self.users_tab)
        self.apply_docs_push_button.setGeometry(QtCore.QRect(190, 450, 75, 23))
        self.apply_docs_push_button.setObjectName("apply_docs_push_button")
        self.delete_user_push_button = QtWidgets.QPushButton(self.users_tab)
        self.delete_user_push_button.setGeometry(QtCore.QRect(420, 100, 121, 23))
        self.delete_user_push_button.setObjectName("delete_user_push_button")
        self.birth_date_date_edit = QtWidgets.QDateEdit(self.users_tab)
        self.birth_date_date_edit.setEnabled(False)
        self.birth_date_date_edit.setGeometry(QtCore.QRect(20, 270, 240, 22))
        self.birth_date_date_edit.setObjectName("birth_date_date_edit")
        self.index.addTab(self.users_tab, "")
        self.interviews_tab = QtWidgets.QWidget()
        self.interviews_tab.setObjectName("interviews_tab")
        self.interview_title_lable = QtWidgets.QLabel(self.interviews_tab)
        self.interview_title_lable.setGeometry(QtCore.QRect(240, 10, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.interview_title_lable.setFont(font)
        self.interview_title_lable.setText("")
        self.interview_title_lable.setObjectName("interview_title_lable")
        self.users_label = QtWidgets.QLabel(self.interviews_tab)
        self.users_label.setGeometry(QtCore.QRect(40, 320, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.users_label.setFont(font)
        self.users_label.setObjectName("users_label")
        self.select_document_combo_box = QtWidgets.QComboBox(self.interviews_tab)
        self.select_document_combo_box.setGeometry(QtCore.QRect(360, 70, 251, 21))
        self.select_document_combo_box.setObjectName("select_document_combo_box")
        self.select_documet_label = QtWidgets.QLabel(self.interviews_tab)
        self.select_documet_label.setGeometry(QtCore.QRect(420, 40, 101, 16))
        self.select_documet_label.setObjectName("select_documet_label")
        self.users_list_widget = QtWidgets.QListWidget(self.interviews_tab)
        self.users_list_widget.setGeometry(QtCore.QRect(20, 340, 251, 81))
        self.users_list_widget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.users_list_widget.setObjectName("users_list_widget")
        self.apply_users_push_button = QtWidgets.QPushButton(self.interviews_tab)
        self.apply_users_push_button.setGeometry(QtCore.QRect(190, 460, 75, 23))
        self.apply_users_push_button.setObjectName("apply_users_push_button")
        self.clear_users_push_button = QtWidgets.QPushButton(self.interviews_tab)
        self.clear_users_push_button.setGeometry(QtCore.QRect(20, 460, 75, 23))
        self.clear_users_push_button.setObjectName("clear_users_push_button")
        self.description_line_edit = QtWidgets.QLineEdit(self.interviews_tab)
        self.description_line_edit.setEnabled(False)
        self.description_line_edit.setGeometry(QtCore.QRect(20, 80, 240, 20))
        self.description_line_edit.setText("")
        self.description_line_edit.setFrame(False)
        self.description_line_edit.setObjectName("description_line_edit")
        self.description_lable = QtWidgets.QLabel(self.interviews_tab)
        self.description_lable.setGeometry(QtCore.QRect(40, 60, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.description_lable.setFont(font)
        self.description_lable.setObjectName("description_lable")
        self.title_line_edit = QtWidgets.QLineEdit(self.interviews_tab)
        self.title_line_edit.setEnabled(False)
        self.title_line_edit.setGeometry(QtCore.QRect(20, 40, 240, 20))
        self.title_line_edit.setText("")
        self.title_line_edit.setFrame(False)
        self.title_line_edit.setObjectName("title_line_edit")
        self.publication_date_lable = QtWidgets.QLabel(self.interviews_tab)
        self.publication_date_lable.setGeometry(QtCore.QRect(40, 110, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.publication_date_lable.setFont(font)
        self.publication_date_lable.setObjectName("publication_date_lable")
        self.title_lable = QtWidgets.QLabel(self.interviews_tab)
        self.title_lable.setGeometry(QtCore.QRect(40, 20, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_lable.setFont(font)
        self.title_lable.setObjectName("title_lable")
        self.chapters_lable = QtWidgets.QLabel(self.interviews_tab)
        self.chapters_lable.setGeometry(QtCore.QRect(40, 160, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.chapters_lable.setFont(font)
        self.chapters_lable.setObjectName("chapters_lable")
        self.delete_document_push_button = QtWidgets.QPushButton(self.interviews_tab)
        self.delete_document_push_button.setGeometry(QtCore.QRect(400, 110, 171, 23))
        self.delete_document_push_button.setObjectName("delete_document_push_button")
        self.publication_date_date_edit = QtWidgets.QDateEdit(self.interviews_tab)
        self.publication_date_date_edit.setEnabled(False)
        self.publication_date_date_edit.setGeometry(QtCore.QRect(20, 130, 200, 22))
        self.publication_date_date_edit.setObjectName("publication_date_date_edit")
        self.chapters_list_widget = QtWidgets.QListWidget(self.interviews_tab)
        self.chapters_list_widget.setEnabled(False)
        self.chapters_list_widget.setGeometry(QtCore.QRect(20, 190, 231, 101))
        self.chapters_list_widget.setObjectName("chapters_list_widget")
        self.index.addTab(self.interviews_tab, "")
        self.new_user = QtWidgets.QWidget()
        self.new_user.setObjectName("new_user")
        self.new_email_line_edit = QtWidgets.QLineEdit(self.new_user)
        self.new_email_line_edit.setGeometry(QtCore.QRect(130, 210, 400, 21))
        self.new_email_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_email_line_edit.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly|QtCore.Qt.ImhLatinOnly)
        self.new_email_line_edit.setMaxLength(24)
        self.new_email_line_edit.setObjectName("new_email_line_edit")
        self.new_birth_date_label = QtWidgets.QLabel(self.new_user)
        self.new_birth_date_label.setGeometry(QtCore.QRect(290, 300, 61, 16))
        self.new_birth_date_label.setObjectName("new_birth_date_label")
        self.new_user_apply_button = QtWidgets.QPushButton(self.new_user)
        self.new_user_apply_button.setGeometry(QtCore.QRect(450, 400, 71, 23))
        self.new_user_apply_button.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.new_user_apply_button.setObjectName("new_user_apply_button")
        self.new_middle_name_line_edit = QtWidgets.QLineEdit(self.new_user)
        self.new_middle_name_line_edit.setGeometry(QtCore.QRect(130, 160, 400, 21))
        self.new_middle_name_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_middle_name_line_edit.setAutoFillBackground(False)
        self.new_middle_name_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_middle_name_line_edit.setMaxLength(30)
        self.new_middle_name_line_edit.setFrame(True)
        self.new_middle_name_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_middle_name_line_edit.setClearButtonEnabled(False)
        self.new_middle_name_line_edit.setObjectName("new_middle_name_line_edit")
        self.new_surname_line_edit = QtWidgets.QLineEdit(self.new_user)
        self.new_surname_line_edit.setGeometry(QtCore.QRect(130, 110, 400, 21))
        self.new_surname_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_surname_line_edit.setAutoFillBackground(False)
        self.new_surname_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_surname_line_edit.setMaxLength(30)
        self.new_surname_line_edit.setFrame(True)
        self.new_surname_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_surname_line_edit.setClearButtonEnabled(False)
        self.new_surname_line_edit.setObjectName("new_surname_line_edit")
        self.new_first_name_line_edit = QtWidgets.QLineEdit(self.new_user)
        self.new_first_name_line_edit.setGeometry(QtCore.QRect(130, 60, 400, 21))
        self.new_first_name_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_first_name_line_edit.setAutoFillBackground(False)
        self.new_first_name_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_first_name_line_edit.setMaxLength(30)
        self.new_first_name_line_edit.setFrame(True)
        self.new_first_name_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_first_name_line_edit.setClearButtonEnabled(False)
        self.new_first_name_line_edit.setObjectName("new_first_name_line_edit")
        self.new_user_clear_button = QtWidgets.QPushButton(self.new_user)
        self.new_user_clear_button.setGeometry(QtCore.QRect(140, 400, 71, 23))
        self.new_user_clear_button.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.new_user_clear_button.setObjectName("new_user_clear_button")
        self.new_birth_date_date_edit = QtWidgets.QDateEdit(self.new_user)
        self.new_birth_date_date_edit.setGeometry(QtCore.QRect(130, 330, 400, 22))
        self.new_birth_date_date_edit.setObjectName("new_birth_date_date_edit")
        self.new_address_line_edit = QtWidgets.QLineEdit(self.new_user)
        self.new_address_line_edit.setGeometry(QtCore.QRect(130, 260, 400, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_address_line_edit.sizePolicy().hasHeightForWidth())
        self.new_address_line_edit.setSizePolicy(sizePolicy)
        self.new_address_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_address_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_address_line_edit.setMaxLength(24)
        self.new_address_line_edit.setObjectName("new_address_line_edit")
        self.index.addTab(self.new_user, "")
        self.new_document = QtWidgets.QWidget()
        self.new_document.setObjectName("new_document")
        self.new_doc_clear_button = QtWidgets.QPushButton(self.new_document)
        self.new_doc_clear_button.setGeometry(QtCore.QRect(140, 340, 71, 23))
        self.new_doc_clear_button.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.new_doc_clear_button.setObjectName("new_doc_clear_button")
        self.new_chapters_line_edit = QtWidgets.QLineEdit(self.new_document)
        self.new_chapters_line_edit.setGeometry(QtCore.QRect(130, 160, 400, 21))
        self.new_chapters_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_chapters_line_edit.setAutoFillBackground(False)
        self.new_chapters_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_chapters_line_edit.setInputMask("")
        self.new_chapters_line_edit.setMaxLength(32767)
        self.new_chapters_line_edit.setFrame(True)
        self.new_chapters_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_chapters_line_edit.setClearButtonEnabled(False)
        self.new_chapters_line_edit.setObjectName("new_chapters_line_edit")
        self.new_doc_apply_button = QtWidgets.QPushButton(self.new_document)
        self.new_doc_apply_button.setGeometry(QtCore.QRect(450, 340, 71, 23))
        self.new_doc_apply_button.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.new_doc_apply_button.setObjectName("new_doc_apply_button")
        self.new_publication_date_date_edit = QtWidgets.QDateEdit(self.new_document)
        self.new_publication_date_date_edit.setGeometry(QtCore.QRect(130, 270, 400, 22))
        self.new_publication_date_date_edit.setObjectName("new_publication_date_date_edit")
        self.new_description_line_edit = QtWidgets.QLineEdit(self.new_document)
        self.new_description_line_edit.setGeometry(QtCore.QRect(130, 110, 400, 21))
        self.new_description_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_description_line_edit.setAutoFillBackground(False)
        self.new_description_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_description_line_edit.setMaxLength(30)
        self.new_description_line_edit.setFrame(True)
        self.new_description_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_description_line_edit.setClearButtonEnabled(False)
        self.new_description_line_edit.setObjectName("new_description_line_edit")
        self.new_title_line_edit = QtWidgets.QLineEdit(self.new_document)
        self.new_title_line_edit.setGeometry(QtCore.QRect(130, 60, 400, 21))
        self.new_title_line_edit.setMaximumSize(QtCore.QSize(500, 16777215))
        self.new_title_line_edit.setAutoFillBackground(False)
        self.new_title_line_edit.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.new_title_line_edit.setMaxLength(30)
        self.new_title_line_edit.setFrame(True)
        self.new_title_line_edit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.new_title_line_edit.setClearButtonEnabled(False)
        self.new_title_line_edit.setObjectName("new_title_line_edit")
        self.new_publication_date_label = QtWidgets.QLabel(self.new_document)
        self.new_publication_date_label.setGeometry(QtCore.QRect(270, 240, 141, 20))
        self.new_publication_date_label.setObjectName("new_publication_date_label")
        self.index.addTab(self.new_document, "")

        self.retranslateUi(main)
        self.index.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "Index"))
        self.email_label.setText(_translate("main", "Email"))
        self.email_line_edit.setPlaceholderText(_translate("main", "email"))
        self.address_label.setText(_translate("main", "Address"))
        self.address_line_edit.setPlaceholderText(_translate("main", "address"))
        self.birth_date_label.setText(_translate("main", "Birth date"))
        self.documents_label.setText(_translate("main", "Documents"))
        self.first_name_label.setText(_translate("main", "First name"))
        self.first_name_line_edit.setPlaceholderText(_translate("main", "first name"))
        self.middle_name_label.setText(_translate("main", "Middle name"))
        self.middle_name_line_edit.setPlaceholderText(_translate("main", "middle name"))
        self.surname_label.setText(_translate("main", "Surname"))
        self.surname_line_edit.setPlaceholderText(_translate("main", "surname"))
        self.select_user_label.setText(_translate("main", "Select user"))
        self.clear_docs_push_button.setText(_translate("main", "Clear"))
        self.apply_docs_push_button.setText(_translate("main", "Apply"))
        self.delete_user_push_button.setText(_translate("main", "Delete this user"))
        self.index.setTabText(self.index.indexOf(self.users_tab), _translate("main", "Users"))
        self.users_label.setText(_translate("main", "Users"))
        self.select_documet_label.setText(_translate("main", "Select document"))
        self.apply_users_push_button.setText(_translate("main", "Apply"))
        self.clear_users_push_button.setText(_translate("main", "Clear"))
        self.description_line_edit.setPlaceholderText(_translate("main", "description"))
        self.description_lable.setText(_translate("main", "Description"))
        self.title_line_edit.setPlaceholderText(_translate("main", "title"))
        self.publication_date_lable.setText(_translate("main", "Publication date"))
        self.title_lable.setText(_translate("main", "Title"))
        self.chapters_lable.setText(_translate("main", "Chapters"))
        self.delete_document_push_button.setText(_translate("main", "Delete this document"))
        self.index.setTabText(self.index.indexOf(self.interviews_tab), _translate("main", "Documents"))
        self.new_email_line_edit.setPlaceholderText(_translate("main", "email"))
        self.new_birth_date_label.setText(_translate("main", "Birth date"))
        self.new_user_apply_button.setText(_translate("main", "Apply"))
        self.new_middle_name_line_edit.setPlaceholderText(_translate("main", "middle name"))
        self.new_surname_line_edit.setPlaceholderText(_translate("main", "surname"))
        self.new_first_name_line_edit.setPlaceholderText(_translate("main", "first name"))
        self.new_user_clear_button.setText(_translate("main", "Clear"))
        self.new_address_line_edit.setPlaceholderText(_translate("main", "address"))
        self.index.setTabText(self.index.indexOf(self.new_user), _translate("main", "New user"))
        self.new_doc_clear_button.setText(_translate("main", "Clear"))
        self.new_chapters_line_edit.setPlaceholderText(_translate("main", "chapter1,chapter2,chapter3"))
        self.new_doc_apply_button.setText(_translate("main", "Apply"))
        self.new_description_line_edit.setPlaceholderText(_translate("main", "description"))
        self.new_title_line_edit.setPlaceholderText(_translate("main", "title"))
        self.new_publication_date_label.setText(_translate("main", "Publication date"))
        self.index.setTabText(self.index.indexOf(self.new_document), _translate("main", "New document"))

